import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { updateStatusUI } from '../../src/ui/status.js';
import { checkBoostStatus, executeBoostMission, claimBoostMissionReward } from '../../src/workflows/boost.js';
import { boostFixture } from '../helpers/boostFixture.js';

test('dashboard renders server progress, reward conditions, selected link and pending states safely', async t => {
    const dom = new JSDOM('<span id="stove-status-boost"></span><span id="stove-status-boost-reward"></span><span id="stove-status-boost-target"></span>');
    const originalDocument = globalThis.document;
    globalThis.document = dom.window.document;
    t.after(() => { globalThis.document = originalDocument; dom.window.close(); });
    const get = id => dom.window.document.getElementById(`stove-status-boost${id}`);
    const f = boostFixture();
    updateStatusUI({ boost: { loading: true } });
    assert.match(get('').textContent, /확인 중/);
    updateStatusUI({ boost: await checkBoostStatus({}, f.deps) });
    assert.match(get('').textContent, /0\/1.*잔여 5회/);
    assert.match(get('-reward').title, /댓글: 1\/1/);
    assert.match(get('-reward').textContent, /조건 진행 중/);
    f.rankings[0].articles[1].title = '<img src=x onerror=alert(1)>';
    await executeBoostMission({}, f.deps);
    updateStatusUI({ boost: await checkBoostStatus({}, f.deps) });
    assert.match(get('').textContent, /1\/1.*잔여 4회/);
    assert.match(get('-reward').textContent, /3,000 F 수령 가능/);
    assert.equal(get('-target').querySelector('a').href, 'https://lounge.onstove.com/view/12');
    assert.equal(get('-target').querySelector('img'), null);
    assert.match(get('-target').textContent, /<img.*966℃/);
    await claimBoostMissionReward({}, f.deps);
    updateStatusUI({ boost: await checkBoostStatus({}, f.deps) });
    assert.match(get('-reward').textContent, /3,000 F 수령 완료/);
    const pending = await checkBoostStatus({}, f.deps);
    pending.mission.rewarded = false;
    pending.mission.current = 0;
    updateStatusUI({ boost: pending });
    assert.match(get('').textContent, /반영 확인 대기/);
    assert.match(get('-reward').textContent, /수령 상태 확인 대기/);
    updateStatusUI({ boost: { success: false, error: 'offline' } });
    assert.match(get('').textContent, /확인 실패/);
    assert.equal(get('-target').querySelector('a'), null, 'failed refresh removes stale target');
    updateStatusUI({ boost: { success: true, notAvailable: true, remainingCount: 5 } });
    assert.match(get('').textContent, /미션 없음/);
});
